# Generated by Django 5.0 on 2025-12-18 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Startup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("IDEA", "Idea Stage"),
                            ("MVP", "MVP Stage"),
                            ("EARLY", "Early Stage"),
                            ("GROWTH", "Growth Stage"),
                            ("SCALE", "Scale Stage"),
                        ],
                        default="IDEA",
                        max_length=10,
                    ),
                ),
                ("industry", models.CharField(max_length=100)),
                ("required_skills", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "founder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="startups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Startup",
                "verbose_name_plural": "Startups",
                "db_table": "startups",
                "ordering": ["-created_at"],
            },
        ),
    ]
